### ISSUE TITLE
Error launching webui "Torch is not able to use GPU; add --skip-torch-cuda-test in the commandline arg"

### ISSUE THREAD

**Issue by SES428** [etherealxx/etherportal-webui-colab#11]
Hi, I was happy that it can run low end devices. Had a bit of fun generating. But soon as I exit the tabs for refreshing. Suddenly got an error when setting it up a new. And I was pretty sad that it needs GPU now, like wtf, it can run just fine a few minutes ago on my phone and now it needs GPU like it doesn't need it for my phone. Please fix this issue, don't add the skip torch argument, because my phone is doing just fine it doesn't need that. Its the google collab's fault for having these errors

**Comment by SES428** [comment]
Oh and here's the issue:

Installing dependencies...
(This process will only happen once per session)

/content
Installing webui...

/content/stable-diffusion-webui
Downloading AnythingV3 model...

/content/stable-diffusion-webui/models/Stable-diffusion
Setting UI configs...

/content/stable-diffusion-webui
Downloading...
From: https://github.com/etherealxx/etherportal-webui-colab/raw/master/notification.mp3
To: /content/stable-diffusion-webui/notification.mp3
100% 57.7k/57.7k [00:00<00:00, 13.2MB/s]
Installing extensions...

/content/stable-diffusion-webui/extensions
fatal: destination path 'stable-diffusion-webui-images-browser' already exists and is not an empty directory.
fatal: destination path 'sd-civitai-browser' already exists and is not an empty directory.
fatal: destination path 'depthmap2mask' already exists and is not an empty directory.
fatal: destination path 'kohya-sd-scripts-webui' already exists and is not an empty directory.
fatal: destination path 'stable-diffusion-webui-model-toolkit' already exists and is not an empty directory.
fatal: destination path 'batchlinks-webui' already exists and is not an empty directory.
fatal: destination path 'Umi-AI' already exists and is not an empty directory.
/content/stable-diffusion-webui/embeddings
Installation Success!
Launching the webui...

/content/stable-diffusion-webui
Python 3.9.16 (main, Dec  7 2022, 01:11:51) 
[GCC 9.4.0]
Commit hash: 22bcc7be428c94e9408f589966c2040187245d81
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/launch.py", line 355, in <module>
    prepare_environment()
  File "/content/stable-diffusion-webui/launch.py", line 260, in prepare_environment
    run_python("import torch; assert torch.cuda.is_available(), 'Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check'")
  File "/content/stable-diffusion-webui/launch.py", line 121, in run_python
    return run(f'"{python}" -c "{code}"', desc, errdesc)
  File "/content/stable-diffusion-webui/launch.py", line 97, in run
    raise RuntimeError(message)
RuntimeError: Error running command.
Command: "/usr/bin/python3" -c "import torch; assert torch.cuda.is_available(), 'Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check'"
Error code: 1
stdout: <empty>
stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/torch/__init__.py", line 217, in <module>
    _load_global_deps()
  File "/usr/local/lib/python3.9/dist-packages/torch/__init__.py", line 177, in _load_global_deps
    raise err
  File "/usr/local/lib/python3.9/dist-packages/torch/__init__.py", line 172, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libgomp-a34b3233.so.1: cannot open shared object file: No such file or directory

**Comment by etherealxx** [comment]
hi, thanks for reporting. have you tried using the colab again? like, start a new colab, don't continue from the previous one.

**Comment by SES428** [comment]
Well I closed the collab and start a new one but it still has issues. Update: Ok it seems waiting for a long time or restarting the phone seemed to solve the problem. Thanks anyways!
