### ISSUE TITLE
About Lora

### ISSUE THREAD

**Issue by Origonzzz** [etherealxx/etherportal-webui-colab#2]
how to install LORA? already try to put in on lora folder but it not detected on stable webui ,already try to refresh it too but still didnt work
![77777737373](https://user-images.githubusercontent.com/125573913/219399056-70d23b55-b088-4f66-8432-3cbd8c6817db.PNG)
![666363636363](https://user-images.githubusercontent.com/125573913/219399063-056bc881-d445-4424-b6a4-fcff966e249f.PNG)

**Comment by etherealxx** [comment]
ah, you're supposed to put it on `/content/stable-diffusion-webui/extensions/sd-webui-additional-networks/models/lora`. I should put it on the readme. This colab is based on camenduru's v2.0 fork. So it doesn't support lora natively.

**Comment by Origonzzz** [comment]
Oooohh I see, thank you so much!!  it works now! <3
![66636366666](https://user-images.githubusercontent.com/125573913/219415530-c1cf3e52-92d8-48c8-83ae-1acedcedb26b.PNG)

**Comment by etherealxx** [comment]
Love to see it😊
If you have some other suggestion, you can put it [here](https://github.com/etherealxx/etherportal-webui-colab/discussions/categories/ideas). This colab is pretty obscure, but i want to make sure it's good enough before i share it to public.
